### ISSUE TITLE
reviewer image showing when environment var is set to 0

### ISSUE THREAD

**Issue by azharkhan** [sakatam/hubot-reviewer-lotto#10]
we are actively using this feature as a part of the engineering process within Slack, so thank you for that. 

one minor annoyance is that even though i've set the environment variable for the avatar to be set as false, it's still showing up when a pull reviewer is assigned. since the size is really big it takes up about 40% of the screen space. 

in my heroku config i've set the following variable: 
`HUBOT_GITHUB_WITH_AVATAR:   0`

**Comment by sakatam** [comment]
@azharkhan sorry for my belated response! and thanks for using this script :) I just fixed the bug so the avatar image will no longer be inserted with your env var setting.
please upgrade the version to v0.7.1.
