### ISSUE TITLE
Include how to get Team ID in documentation

### ISSUE THREAD

**Issue by jefheaton** [sakatam/hubot-reviewer-lotto#15]
The docs don't mention how you can get the actual ID of your desired Github team. I mistakenly added just the name of the team until I went searching around the Github API. 

This tutorial is useful: http://fabian-kostadinov.github.io/2015/01/16/how-to-find-a-github-team-id/

**Comment by sakatam** [comment]
just added a link to the tutorial. thanks a lot!
